package Personagens;

public class Main {

    Personagem guerreiro = new Jogavel("Alexander", "Guerreiro", 200, 20, 45, "Um combatente corpo a corpo especializado em combate direto e resistência física. Ele pode ter habilidades de ataque poderosas, como golpes com espadas ou a capacidade de usar escudos para se proteger.", "Alexander, um guerreiro corajoso de uma aldeia pacífica, perdeu sua família em uma invasão cruel. Ele lutou com bravura, mas não conseguiu impedir a destruição. Sua família foi capturada e executada diante de seus olhos. Desde então, Alexander vive em profunda tristeza e culpa, vagando pelas terras em busca de redenção.", "O guerreiro canaliza sua raiva em um poderoso golpe com a espada, causando dano significativo e diminuindo temporariamente a defesa do inimigo. É uma habilidade devastadora que impacta o campo de batalha (dano = 70)", "A tenacidade do guerreiro Alexander é verdadeiramente impressionante. Quando sua vida está em seu limite, sua determinação intensifica-se, concedendo-lhe uma última reserva de energia. Quando sua vida chegar a 20%, seu dano aumenta em 30%", 70, 60, 50, 30, 0, 0);

    Personagem mago = new Jogavel("Aria", "Mago", 140, 150, 30, "Um usuário de magia que possui um vasto conhecimento e habilidades mágicas. O mago pode lançar feitiços de ataque. Ele pode ser frágil fisicamente, mas compensa isso com suas habilidades mágicas.", "Aria, uma jovem maga excepcionalmente talentosa desde a infância, teve sua vida drasticamente alterada quando uma guerra brutal entre reinos foi deflagrada. Nesse terrível conflito, sua família foi alvo de uma facção inimiga determinada a conquistar o poder dos magos. Aria, a última sobrevivente de sua linhagem, viu seus entes queridos serem cruelmente assassinados diante de seus olhos. Desamparada e sem ter para onde ir, Aria perambulou pelas terras devastadas pela guerra, carregando consigo o peso avassalador da perda e da solidão. Sentindo-se incapaz de lidar com a dor dilacerante, ela se refugiou em uma torre antiga e abandonada, buscando ali algum tipo de segurança e refúgio contra o mundo cruel que a cercava.", "Aria é capaz de convocar uma devastadora chuva de meteoros do céu. Ao canalizar sua energia mágica, ela pode conjurar uma tempestade de rochas flamejantes que caem do firmamento, causando estragos nos inimigos e no ambiente ao redor. (dano = 85)", "Aria possui uma habilidade passiva chamada Percepção Arcana, que lhe confere uma sensibilidade aguçada aos fluxos de energia mágica ao seu redor. Com essa habilidade, não existem enigmas que ela não consegue resolver.", 85, 0, 100, 70, 0, 0);

    Personagem arqueiro = new Jogavel("Ethan", "Arqueiro", 150, 50, 35, "Um especialista em ataques de longo alcance e precisão. O arqueiro usa arcos e flechas para atacar inimigos à distância.", "Ethan, após testemunhar o assassinato de sua esposa por saqueadores, embarcou em uma jornada de vingança. Com sua habilidade excepcional como arqueiro, enfrentou desafios e inimigos poderosos, até finalmente chegar ao covil dos responsáveis. Usando suas flechas certeiras, eliminou os saqueadores um por um. Assim, o arqueiro Ethan se tornou um símbolo de justiça e redenção, um guardião incansável que lutava para tornar o mundo um lugar melhor. Sua história se espalhou e seu nome foi reverenciado por aqueles que ele ajudou e inspirou.", "A habilidade Flecha Perfurante permite que o arqueiro concentre seu foco e precisão para lançar uma flecha de forma extraordinária. Essa flecha é especialmente afiada e projetada para perfurar defesas robustas e armaduras, atingindo o alvo com grande impacto. (Dano = 100)", "A habilidade passiva Precisão Implacável confere ao arqueiro uma mira excepcionalmente precisa e a capacidade de acertar seus alvos com precisão letal. Seus ataques são caracterizados por uma precisão inigualável, permitindo que suas flechas atinjam os pontos mais vulneráveis dos inimigos com extrema eficiência.", 100, 0, 85, 75, 0, 0);

    Personagem assassino = new Jogavel("Erik", "Assassino", 150, 50, 40, "Um assassino silencioso, conhecido por seu talento incomparável em eliminar seus alvos com eficiência e frieza.", "Erik, um assassino treinado desde a infância em uma guilda cruel, perdeu sua conexão com a bondade e tornou-se implacável. As memórias das vidas que ele tirou atormentam-no, corroendo sua alma e envolvendo-o em agonia constante. Por trás de cada missão cumprida, Erik buscava desesperadamente uma maneira de se redimir e escapar do ciclo interminável de violência. Ele ansiava por encontrar um propósito maior e resgatar sua humanidade perdida.", "Lâmina Sombria: Infunde a arma de Erik com uma energia sombria, aumentando seu poder e letalidade. (dano = 80)",  "Sombra Silenciosa, Erik possui a habilidade de se camuflar e se esconder nas sombras com maestria. Sua presença se torna quase indetectável. (cura 100 de vida)", 80, 0, 100, 60, 0, 0);

    Personagem alquimista = new Jogavel("Edward", "Alquimista", 0, 0, 0, null, "Edward, um jovem alquimista talentoso e dedicado, embarca em uma jornada para desvendar os segredos da alquimia e corrigir um erro trágico. Em sua ultima aventura, ele enfrentou perigos, desvendou conspirações e enfrentou desafios mortais. Com suas habilidades alquímicas e sua coragem inabalável, ele se tornou símbolo de esperança e inspiração, restaurando a paz em seu mundo e descobrindo o verdadeiro significado da alquimia.", "A habilidade Explosão Alquímica permite a Edward canalizar uma quantidade enorme de energia alquímica em um único ponto, desencadeando uma explosão devastadora. (dano = 70)", "A habilidade passiva de cura de Edward, chamada Toque Alquímico, permite que ele utilize sua alquimia para acelerar o processo de cicatrização e regeneração. (cura = 60)", 70, 60, 100, 50, 0, 0);

}
